[project]
name = "cat-dog-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ivyTS13", email = "crosanna256@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
cat-dog-classifier = "cat_dog_classifier:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
